### ISSUE TITLE
setup and breakdown methods

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#139]
What do you think about adding setup and breakdown methods for individual benchmarks? Right now we have the Benchmark.startupHook but that runs for every benchmark. That forces me to make a completely new target for every benchmark that has some small setup code in order to not unnecessarily run that for every benchmark that doesn't use it in my target.

**Comment by hassila** [comment]
It's implicitly already there, basically like this:

```swift
let benchmarks = {
 Benchmark("xxx") { benchmark in
  // Do individual setup here
    benchmark.startMeasurement()
    for _ in benchmark.scalingFactor {
 /// bench code here
    }
    benchmark.stopMeasurement()
// do individual teardown here
  }
}
```

Then only the actual code between start/stop measurement is measured, the setup/teardown would be excluded.

Does this solve your problem?

**Comment by JaapWijnen** [comment]
Oh absolutely! Thanks!
