### ISSUE TITLE
Defining benchmarks across different files

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#145]
Would it be possible to define benchmarks across multiple files? say x benchmarks of type A in file 1 and y benchmarks of type B in file 2? Saves creating as much targets as I'm currently making for our repos haha. Which is already very heavy on the amount of modules.

**Comment by hassila** [comment]
Just have one file with the normal "let benchmarks =" code call freestanding functions in other files that register the benchmarks as usual? 

You can have any number of files this way for a benchmark target. 

Then prefix the benchmarks with the type so you easily can use regex filtering to run appropriate subsets easily.

**Comment by hassila** [comment]
@JaapWijnen does that work for you?

**Comment by JaapWijnen** [comment]
Haven't been able to try it yet sorry! But thanks for the tip!
