### ISSUE TITLE
sandboxing

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#152]
Is there some kind of sandboxing going on within the plugin? I'm running into the following error at the moment in one of my benchmarks. 
```
stdout:
stderr:
<unknown>:0: error: unable to open output file '/var/folders/_w/tgplyjrn1pd5zg417w8_jrgr0000gn/C/clang/ModuleCache/2LO8DN2T79G1C/CoolProp-1S840FRS8BXI3.pcm': 'Operation not permitted'
```
If I run the exact same test without the benchmark api around it it all runs fine

**Comment by hassila** [comment]
Yeah, we’re sandboxed by swiftpm - for network/disk access you need to either allow writing to certain directories or disable the sandbox, some hints: https://swiftpackageindex.com/ordo-one/package-benchmark/1.4.8/documentation/benchmark/runningbenchmarks

**Comment by hassila** [comment]
So either specify `--allow-writing-to-package-directory` or `—disable-sandbox`

**Comment by JaapWijnen** [comment]
Yeah using --disable-sandbox worked thanks a lot! Life saver
