### ISSUE TITLE
regex examples

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#161]
Would you have some regex examples to use with for example a skip filter? I think I'm missing something here, can't get that flag to work for me

**Comment by hassila** [comment]
Try something like eg. (From mobile to the best of my memory but should give a hint - let me know if it helps):

Case sensitive contains "mystuff":

\.*mystuff\.*

Beginning with xxx:

xxx\.*

Suffix of PERF
\.*PERF

Any five chars followed by "suffix":

\.\.\.\.\.suffix

Basically it's the standard new regex specified by swift - there's tons of flexibility you can find some more examples from links here:

https://www.hackingwithswift.com/swift/5.7/regexes

**Comment by hassila** [comment]
`swift package benchmark --filter ".*autoresizing"`

is a concrete example...

**Comment by JaapWijnen** [comment]
Perfect! Thanks a lot
