### ISSUE TITLE
Profiling benchmark

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#163]
Hey there! I tried to profile a certain benchmark the other day (from Xcode) and ran into the following error when it tried to build the benchmark executable target for profiling: 
`Build failed because libjemalloc.dylib is missing a required architecture. Would you like to build for Rosetta instead?`
I'm on an M1 MacBook pro and I can see libjemalloc.dylib in my /opt/homebrew/lib folder. 
Any ideas on how to get past this? 
(I get the option to build for rosetta but I want to avoid that of course)

**Comment by hassila** [comment]
Yeah, it's an issue with Xcode trying to build for all architectures in profiling mode - we've filed a bug report for it (don't have the FB number handy, but please file a report you too, basically it will always build for both x86 and ARM).

The workaround is to set `BENCHMARK_DISABLE_JEMALLOC` to true so that the malloc support is disabled from benchmark, this should work from the command line only though. 

If you have trouble doing it from Xcode (due to FB12076783 - "Xcode should allow setting of environment variables that are picked up by SwiftPM package resolution" - feel free to file a Feedback there too) , you can have a local copy of benchmark which you simply hard code this by replacing a single line:

```swift
// let disableJemalloc = ProcessInfo.processInfo.environment["BENCHMARK_DISABLE_JEMALLOC"]
let disableJemalloc = Optional("1")
```

I could use Instruments for a benchmark through this approach, let me know how it works out for you.

HTH

**Comment by hassila** [comment]
Here is also this more hard core workaround for the Xcode issue:

```
// To be able to pick up the correct environment variable in Package.swift, the only workaround right now is:

$ killall Xcode
$ BENCHMARK_DISABLE_JEMALLOC=1  open Package.swift
```

**Comment by hassila** [comment]
@JaapWijnen did you have any luck?

**Comment by JaapWijnen** [comment]
@hassila Thanks for checking in. Not yet I'm running into other issues that are blocking me where one of my benchmarks fails with the following error: `process failed: WaitPIDError("no command sent to controlled process.")` But I can't reproduce that error when running without the benchmark package. So I'm not sure how to get to the bottom of the issue. Is there a way to propagate a clearer error message back to the process running the Benchmark plugin? I'm guessing I'm hitting some kind of runtime error that has to do with a bug in Swift (we're using the newest toolchain and this is often the case) But it's very hard to narrow down what the actual culprit is due to just getting the `process failed: WaitPIDError("no command sent to controlled process.")` error

**Comment by hassila** [comment]
@JaapWijnen did you try any of the approaches listed in the section [Troubleshooting problems](https://swiftpackageindex.com/ordo-one/package-benchmark/1.6.5/documentation/benchmark/runningbenchmarks#Troubleshooting-problems) ?

That way you can run the offending test in LLDB to get some more useful errors.

**Comment by JaapWijnen** [comment]
I did but it didn't give me a lot more info unfortunately. 
```
Process 60891 stopped
* thread #2, queue = 'com.apple.root.default-qos.cooperative', stop reason = EXC_BREAKPOINT (code=1, subcode=0x100687dd0)
    frame #0: 0x0000000100687dd0 SimulatorPerformanceBreakdownBenchmarks`Simulator.SamplerPlugin.sample(plugin: PluginInterface.PluginInterface, currentTime: Swift.Double) -> () + 392
SimulatorPerformanceBreakdownBenchmarks`Simulator.SamplerPlugin.sample(plugin: PluginInterface.PluginInterface, currentTime: Swift.Double) -> ():
->  0x100687dd0 <+392>: brk    #0x1
    0x100687dd4 <+396>: add    x0, x24, #0x40
    0x100687dd8 <+400>: add    x1, sp, #0x98
    0x100687ddc <+404>: bl     0x10007e94c               ; outlined init with copy of Logging.Logger at <compiler-generated>
Target 0: (SimulatorPerformanceBreakdownBenchmarks) stopped.
(lldb) exit
```

**Comment by hassila** [comment]
Try building with 'swift build' and run the debug version without lldb, hopefully you get a decent backtrace then?
