### ISSUE TITLE
plugin validation with xcode build

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#173]
I'm running into issues on CI where I'm building my code for iOS and have to use the xcodebuild command which fails with the following error.
```
error: the following command failed with exit code 1 but produced no further output
Validate plug-in “BenchmarkPlugin” in package “package-benchmark”
```
Any others that have dealt with this? I unfortunately can't add a OS condition to a plugin declaration in the Package.swift file.

**Comment by hassila** [comment]
Hey, sorry can't respond until mid august due to vacation time for everyone that could have input - hope someone else may chime in before.

**Comment by hassila** [comment]
Please reopen if you have further information.

**Comment by simlay** [comment]
Well, I (mostly) figured it out. I'm not sure why but adding the `executableTarget` causes the `xcodebuild` scheme to change name and be suffixed with `-Package`. Then once I tried this I did run into a "Plugin validation" error. I found that [someone had this issue with swiftlint](https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305) and so adding in a `-skipPackagePluginValidation` fixes `xcodebuild ... test` fixes certain errors.

Definitely out of the scope of this issue but I then get various linktime/build errors:
* my iOS build says `cannot find 'getRusage' in scope`
* tvOS: `Undefined symbol:` for `_mallctlbymib`, `_mallctlnametomib`, `_malloc_stats_print`
* watchOS: ` No such module 'CDarwinOperatingSystemStats'

**Comment by hassila** [comment]
Hey @simlay 

> Well, I (mostly) figured it out. I'm not sure why but adding the `executableTarget` causes the `xcodebuild` scheme to change name and be suffixed with `-Package`. Then once I tried this I did run into a "Plugin validation" error. I found that [someone had this issue with swiftlint](https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305) and so adding in a `-skipPackagePluginValidation` fixes `xcodebuild ... test` fixes certain errors.
> 
> Definitely out of the scope of this issue but I then get various linktime/build errors:
> 
> * my iOS build says `cannot find 'getRusage' in scope`
> * tvOS: `Undefined symbol:` for `_mallctlbymib`, `_mallctlnametomib`, `_malloc_stats_print`
> * watchOS: ` No such module 'CDarwinOperatingSystemStats'

Yeah, a bit out of scope for this issue - we've only been running on macOS and Linux really, so I'm not surprised if there's some friction for other Apple platforms - for tvOS you might try disabling the jemalloc support as mentioned here:
https://swiftpackageindex.com/ordo-one/package-benchmark/1.22.4/documentation/benchmark/runningbenchmarks#Running-benchmarks-in-Xcode-and-using-Instruments-for-profiling-benchmarks

for iOS, there is an ifdef in `OperatingSystemStatsProducer+Darwin.swift`:

```
        #if os(macOS)
```
 that makes getRusage to be unavailable - happy to take a PR on that ifdef (and any others if there's more) needed to get it to work on iOS (we currently don't build any benchmarks there internally).

Please open separate issues for any follow up that is concretely actionable if you don't mind?

**Comment by hassila** [comment]
@simlay I added the ifdefs here:
https://github.com/ordo-one/package-benchmark/releases/tag/1.23.4

Hopefully that makes it work on iOS at least, do give it a try.
