### ISSUE TITLE
Fix ASAN failures

### ISSUE THREAD

**Issue by hassila** [ordo-one/package-benchmark#205]
Quick Look and it looks like a false positive when e.g. appending to arrays.

**Comment by dabrahams** [comment]
It's actually a leak sanitizer failure, a fact of which  you are obviously already aware (I found your bug report).  Why not just run the ASAN tests on MacOS, disable the leak sanitizer, or… at least…remove the badge for that workflow so that it doesn't look like I need to worry about using this package when I look at the README?  You've got a lot of alarming looking badges!

**Comment by hassila** [comment]
Thanks @dabrahams should nice it to macOS. Just to clarify "a lot of alarming badges" - which other badges do you find alarming?

**Comment by dabrahams** [comment]
Swift and platforms badges are red.  Codecov too but that's a separate issue.

**Comment by hassila** [comment]
Oh, that's the color choice (orange) of swift package index which renders those - maybe another color would be better by default if it viewed as some error wdyt @finestructure ?

**Comment by hassila** [comment]
I believe it is chosen to match the swift logo though.

**Comment by finestructure** [comment]
Yes, it's the "Swift orange". I vaguely remember that the colour was configurable via some parameter but I'm not 100% sure. Do you want to raise an issue and we'll take a look?

**Comment by hassila** [comment]
Will do, thanks!

**Comment by hassila** [comment]
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/3410 for that.

**Comment by hassila** [comment]
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3411

**Comment by hassila** [comment]
@dabrahams 

Fixed this by moving to macOS for running ASAN/LSAN as you suggested.

 Above https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3411 for making the badges not signal CI state.

The codecov badge will eventually be fixed as test code coverage improves.
