### ISSUE TITLE
Specifying parameterized benchmarks and performing parameter sweeps

### ISSUE THREAD

**Issue by loonatick-src** [ordo-one/package-benchmark#224]
I want to run a "family of benchmarks" as described in the [google benchmark documentation](https://github.com/google/benchmark/blob/main/docs/user_guide.md#passing-arguments). E.g. running the same benchmark for different thread counts, different problem sizes etc.

The only option that I can come up with after going through the docs is manually duplicating existing benchmarks. I was unable to find anything in the documentation regarding this. Is this possible in release 1.22.0?

**Comment by hassila** [comment]
For sure, just try something like this for running 7 different benchmarks with different parameterization:

```
import Benchmark

let benchmarks = {
    let tableCounts = (0..<10).map { 1 << $0 } // 1, 2, 4, ... 512
   
    tableCounts.forEach { tableCount in
        Benchmark("TransactionsWith\(tableCount)Tables") { benchmark in
             print("Running benchmark for \(tableCount)")
    }
}
```

**Comment by hassila** [comment]
See documentation updated in 
https://github.com/ordo-one/package-benchmark/releases/tag/1.22.1
