### ISSUE TITLE
Could not build Objective-C module 'JWTKit'

### ISSUE THREAD

**Issue by ptoffy** [ordo-one/package-benchmark#232]
I'm trying to run benchmarks on [JWTKit](https://github.com/vapor/jwt-kit), unfortunately I get
```
error: could not build Objective-C module 'JWTKit'
```
on the `import JWTKit` line. I just followed the getting started part of the README:
 - installed `jemalloc`: `brew install jemalloc`
 - ran `swift package --allow-writing-to-package-directory benchmark init Signing` 
 - built and ran benchmarks with the default benchmark file

up until then everything worked. When importing JWTKit in the benchmark file and building, the error appears. Not sure if it's an issue with this repo or a SwiftPM thing but wanted to check to be sure

Thanks!

**Comment by ptoffy** [comment]
Forgot to add JWTKit to the benchmark's target's dependencies 🤦‍♂️

**Comment by hassila** [comment]
Yeah. That misleading error is always missing dependency.
