### ISSUE TITLE
Improved Docs for iOS Projects?

### ISSUE THREAD

**Issue by iainsmith** [ordo-one/package-benchmark#233]
Thank you for producing such a wonderful package. I recently wanted to run some benchmarks that have a hard UIKit dependency, and I hit some issues when following the documentation which assumes a mac/linux environment (unless I missed something). 

Given the prevalence of iOS swift code, having some additional documentation for this case would help get iOS teams onboarded.

**Comment by hassila** [comment]
We'd be happy to take a PR if there's anything specific that needs to be taken into consideration- we currently don't work on iOS so hard to document for us. Any improvements appreciated.

**Comment by hassila** [comment]
More concretely what was the problem?

**Comment by ktoso** [comment]
Chiming in as maintainer of the Distributed language feature -- what are you trying to do achieve on iOS @iainsmith?
In general I see this library is -- similar to the DistributedCluster library -- forming clusters and maintaining strong membership between nodes. This in general isn't an approach that one would be taking with devices -- as they're more ephemeral in their presence in network somewhat...

Would some other kind of distributed actor system implementation be more suitable for your needs?
Could you explain your use case and perhaps we can point at some directions to explore?

**Comment by hassila** [comment]
@ktoso seems you commented in context of some DA system, this issue is in context of Benchmark docs, probably ended up in wrong issue?

**Comment by ktoso** [comment]
Oh boy, ignore me -- I wrongly assumed this comment was in the distributed system package 😅 Let me remove the comment, it's just noise :)

**Comment by hassila** [comment]
@iainsmith I tried to add the relevant iOS ifdefs here, not sure if that is enough for it to work as expected, but give it a try. Happy to take any other concrete suggestions on improvements, but as mentioned we don't do iOS so hard for us to know what's missing really... :-)

https://github.com/ordo-one/package-benchmark/releases/tag/1.23.4
