### ISSUE TITLE
Any API for specifying `minIterations` on a benchmark?

### ISSUE THREAD

**Issue by vanvoorden** [ordo-one/package-benchmark#238]
Hi! I'm running some benchmarks that I want to guarantee to run for `n` iterations without timing out. I'm trying this:

```swift
Benchmark.defaultConfiguration.maxDuration = SOME_LARGE_DURATION
Benchmark.defaultConfiguration.maxIterations = .count(n)
```

This seems to work… but is there any alternative API for me to use for that? Something like `minIterations` or a `DISTANT_FUTURE` flag that can be passed for a duration?

**Comment by hassila** [comment]
Hi,

That is indeed the intended approach - usually even if you want to run N iterations you probably want to timeout at some point especially for eg. CI - but we haven't added any convenience wrapper to duration for that (yet)

**Comment by vanvoorden** [comment]
@hassila Thanks!
