### ISSUE TITLE
Support for memcpy metrics

### ISSUE THREAD

**Issue by jcavar** [ordo-one/package-benchmark#241]
Hello,

Thank you for this great package!

I was wondering if it would be possible to provide a hook and metric for `memcpy`?

**Comment by hassila** [comment]
Probably would want to capture the number of loads/stores rather in that case so the actual mechanism used for the copying doesn't matter - or is there some specific reason why you'd want to capture just memcpy exactly?

Would need some research and look at how the data can be captured (e g. Look at perf on Linux, and something similar on macOS) - happy to consider a PR for that if you find some way to capture it without requiring privilege escalation. 

What is the reason you want to measure this?

**Comment by jcavar** [comment]
> Probably would want to capture the number of loads/stores rather in that case so the actual mechanism used for the copying doesn't matter - or is there some specific reason why you'd want to capture just memcpy exactly?

I was doing some experiments and benchmarks around the performance impact of `borrowing` and `consuming` modifiers [here](https://infinum.com/blog/swift-ownership/). It was great to see a number of retain/release operations for particular benchamark, so I missed something similar for value types.

But I see your point, I think I was too quick to assume that these translate to `memcpy`.

> Would need some research and look at how the data can be captured (e g. Look at perf on Linux, and something similar on macOS) - happy to consider a PR for that if you find some way to capture it without requiring privilege escalation.

Got it, at some point I would like to look into it. As well as some other potential features (e.g. `swift_beginAccess` and `swift_endAccess`)

**Comment by hassila** [comment]
That would be great, also begin/end access would be super to capture!

**Comment by hassila** [comment]
And very nice blog post by the way! 👍🏻🎉

**Comment by jcavar** [comment]
Thank you! Will close this task since there is no immediate action.
