### ISSUE TITLE
Can `--format markdown` produce legit markdown tables?

### ISSUE THREAD

**Issue by vanvoorden** [ordo-one/package-benchmark#245]
Hi! I'm trying to run some benchmarks with the `--format markdown` option:

https://github.com/Swift-CowBox/Swift-CowBox-Sample-Data/blob/main/2024-04-25-1-struct.txt#L81-L98

This looks like it is producing the default Benchmarks "table" with markdown backticks (```). Which is good… but different than producing a first-class markdown table.

https://github.com/ordo-one/package-benchmark/blob/1.23.1/Plugins/BenchmarkTool/BenchmarkTool%2BPrettyPrinting.swift#L130-L132

Is there currently an option to format that table in markdown? Has this been discussed or tracked before? Thanks!

**Comment by vanvoorden** [comment]
Maybe adding a new `--format github` option would be more appropriate than doing too many changes on the existing `--format markdown` option. Any thoughts about that?

**Comment by hassila** [comment]
I don't mind changing the existing format for markdown, it was always intended to be aimed at GitHub really.

**Comment by vanvoorden** [comment]
@hassila Do you know if anyone is already working on that? I can try! Do you know anything about the upstream status of the `TextTable` repo? Is that still being maintained?

I could try a diff on the `TextTable` fork and then try a diff on the `Benchmark` repo. How does that sound?

**Comment by vanvoorden** [comment]
@hassila After taking a closer look… I think that the existing `PipeFormat` is just the same as modern `GitHub`. It's possible the `github` style in the original python project is just an artifact from the legacy `github` format before alignment was added.

What is your strategy for unit testing the whole print flow? How would I test a diff (other than manually launching benchmarks from command line)?

**Comment by hassila** [comment]
No nice testing strategy for print output formats I'm afraid, just manual testing really. But in this case, I think the change should be as simple as changing `Style.fancy` to be conditionalized and use `.PipeFormat` if we are in markdown output mode then? Just needs to test it...

**Comment by vanvoorden** [comment]
```diff
- table.print(scaledResults, style: Style.fancy)
+ table.print(scaledResults, style: format == .markdown ? Style.pipe ? Style.fancy)
```

@hassila Probably this should be good enough. Is there a specific benchmark already defined in the package that is good enough for testing?

**Comment by hassila** [comment]
Yeah, that should do it (but I believe there are a few places that needs fixed in the same file for delta vs normal etc). 

Easiest way to test manually is just to run from command line and copy-paste into a dummy GitHub repo with a markdown file and preview it there

**Comment by vanvoorden** [comment]
> I believe there are a few places that needs fixed in the same file for delta vs normal etc

@hassila Hmm… I think I could have a diff ready to migrate those `print` statements to the `pipe` style. That might just be a few LOC. For unit testing… I might have some ideas about a refactoring here that might make unit testing easier and practical. That one might be 50 to 100 LOC… but could make it a lot easier to write an automated test against all this logic. What would your thoughts be about that? Has manual testing slowed you down before on this logic? Is this logic that you expect to iterate on and extend this year? Would automated unit tests increase engineering velocity in a big way?

I'm a big fan of unit testing… but if we feel like this code is overall stable and we don't expect many more changes this year then maybe it's for the best to keep things as they are. But if you had been planning to make things testable or wanted improved testability to move faster I might have some ideas on a refactoring. What are your thoughts about that?

**Comment by hassila** [comment]
I in general do like unit testing too, but maybe put that on pause for this specific code for the moment - no changes planned really (during the remainder of this  I'd expect primarily bug fixes and possibly new metrics, then likely move to Swift 6 and migrate tests to the new testing infrastructure that is in the pipeline - that might be a good time to revisit testing of the text output and would be happy to have some help with that when we get there).

**Comment by vanvoorden** [comment]
@hassila Sounds good. I think I could have the small diff with manual testing in place early next week. Thanks!

**Comment by hassila** [comment]
Done in #247 , thanks!
