### ISSUE TITLE
Signpost for startBenchmark/stopBenchmark

### ISSUE THREAD

**Issue by dnadoba** [ordo-one/package-benchmark#259]
The signposts introduced in https://github.com/ordo-one/package-benchmark/pull/182 are very valuable. 
It would be great if they would also respect if the benchmark is stared/stoped manually.
I guess this requires another set of signposts as we don't know upfront if `Benchmark.startBenchmark()` is called or not.

**Comment by hassila** [comment]
That's a good idea. Don't remember the details of the signpost api, but you are likely right.

**Comment by hassila** [comment]
@dnadoba you can give https://github.com/ordo-one/package-benchmark/pull/260 a spin If you like
