### ISSUE TITLE
`--help` doesn't show the help text

### ISSUE THREAD

**Issue by MahdiBM** [ordo-one/package-benchmark#268]
```bash
swift package benchmark --help
```
Results in:
```bash
Build of product 'BenchmarkTool' complete! (15.56s)
Unknown option/flag specfied: ["--help"]
error: invalidArgument
```

**Comment by hassila** [comment]
`swift package benchmark help` will show it - but so should be the case for unknown options/flags... Should be fixed.

**Comment by MahdiBM** [comment]
I just noticed this doesn't show a help text either:

```bash
benchmark run help   
```

**Comment by hassila** [comment]
Should be fixed by https://github.com/ordo-one/package-benchmark/pull/284 now, if you can please have a go testing against that (it will be merged fairly soon).

**Comment by hassila** [comment]
Merged and should be fixed now.
