### ISSUE TITLE
Docs explaining how to use static threshold files

### ISSUE THREAD

**Issue by MahdiBM** [ordo-one/package-benchmark#269]
From Slack:

> There is either no mention of how to write static threshold files, or at least it’s not linked where threshold is mentioned, like [here](https://swiftpackageindex.com/ordo-one/package-benchmark/1.25.0/documentation/benchmark/creatingandcomparingbaselines).
I figured this out by looking at what SwiftNIO has, but even then, I had to trial-and-error to find out that e.g. the number you put in the threshold files must be in the base units (e.g. nanoseconds) not what you set in the configuration.

I didn't even know you're not supposed to manually create those threshold json files until @hassila mentioned it.

**Comment by hassila** [comment]
Should be fixed by https://github.com/ordo-one/package-benchmark/pull/284 now, if you can please have a go testing against that (it will be merged fairly soon).

**Comment by hassila** [comment]
I think this can be closed with the new thresholds, let's follow up with new issues if there are further improvements?
