### ISSUE TITLE
`--format metricP90AbsoluteThresholds` is unexpected to me

### ISSUE THREAD

**Issue by MahdiBM** [ordo-one/package-benchmark#271]
Currently we use a command like this to update the thresholds in CI, using [this CI file](https://gist.github.com/MahdiBM/53adae524092b7a8fcddb61aa7f42a7d) I've put together:

```bash
swift package --allow-writing-to-directory Benchmarks/Thresholds/ benchmark --format metricP90AbsoluteThresholds --path Benchmarks/Thresholds/
```

The format is ... weird. I would have expected something like:

```bash
swift package --allow-writing-to-directory Benchmarks/Thresholds/ benchmark update-thresholds --metric p90 --form absolute/relative --path Benchmarks/Thresholds/
```

This will also allow selecting different "metrics" and different "forms" (perhaps "form" isn't the ideal word, but you get the idea).

I don't know the package in-and-out, so i give it a chance that what I propose is problematic in other ways ... so I'm open to a discussion if you think so.

**Comment by hassila** [comment]
Should be fixed by https://github.com/ordo-one/package-benchmark/pull/284 now, if you can please have a go testing against that (it will be merged fairly soon).

**Comment by hassila** [comment]
I think this can be closed with the new thresholds, let's follow up with new issues if there is anything weird there.
