### ISSUE TITLE
Absolute Thresholds from Benchmark-Setup are not respected

### ISSUE THREAD

**Issue by fred-sch** [ordo-one/package-benchmark#282]
Running the following benchmark with `swift package benchmark baseline check --check-absolute`

```swift
    Benchmark(
        "p90Sleep" ,
        configuration: .init(metrics: .all, thresholds: [.wallClock: .init(absolute: [.p90: .milliseconds(100)])])
    ) { _ in
        sleep(1)
    }
```

I was expecting it to fail. Instead the output was just:

`Baseline 'Current_run' is EQUAL to the defined absolute baseline thresholds. (--check-absolute)`

I looked into it and it seems that because of [BenchmarkTool+Operations#L170](https://github.com/ordo-one/package-benchmark/blob/99365fb80289b388a9fd87bc2eb2903b4b201591/Plugins/BenchmarkTool/BenchmarkTool%2BOperations.swift#L170) only p90-thresholds from a file `checkAbsolutePath` are considered.

**Comment by hassila** [comment]
Thanks for the report, will soon be a significant update to threshold handling, will review this in that context - hope to have a PR up in the near future.

**Comment by hassila** [comment]
Should be explained by documentation and updated static threshold support in https://github.com/ordo-one/package-benchmark/pull/284

Basically what you define in the benchmark itself, is the *threshold tolerance* for checking, while an actual static threshold value (now) will be stored with `swift package benchmark thresholds update` ... 

Please have a look and hope this clears things up.

**Comment by terraputix** [comment]
Thanks for the quick reply! 

I agree that https://github.com/ordo-one/package-benchmark/pull/284 should resolve/clarify the problem. I think mostly I was confused by the docs, the naming of the parameter (which you changed to `thresholdTolerance` now) and a missing error message when no p90 thresholds were found. I see all these things addressed in your PR!

**Comment by fred-sch** [comment]
Thanks for the quick reply! 

I agree that https://github.com/ordo-one/package-benchmark/pull/284 should resolve/clarify the problem. I think mostly I was confused by the docs, the naming of the parameter (which you changed to `thresholdTolerance` now) and a missing error message when no p90 thresholds were found. I see all these things addressed in your PR!

**Comment by hassila** [comment]
Super, closing this then, thanks.
