### ISSUE TITLE
Package SPIManifest seems to be unused

### ISSUE THREAD

**Issue by JaapWijnen** [ordo-one/package-benchmark#46]
Saw there's a dependency on https://github.com/SwiftPackageIndex/SPIManifest which is not used at the moment!

**Comment by hassila** [comment]
Its to get access to the validation plugin "swift package plugin validate-spi-manifest" for the .spi.yml

**Comment by hassila** [comment]
See https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/0.13.0/documentation/spimanifest/validation for details...

**Comment by JaapWijnen** [comment]
Got it sorry about that! :) Didn't know they provided that so that's really useful to know haha, thanks!
