### ISSUE TITLE
`swift test` failing locally due to (FB12061292)

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#60]
Likely a question more than a bug report. I checked out the repo (`main` branch), installed jemalloc per the prerequisites (`brew install jemalloc`). After that `swift build` worked fine, but `swift test` in the repository failed for me locally:

```
Building for debugging...
[10/10] Linking BenchmarkPackageTests
Build complete! (7.69s)
error: Exited with signal code 11
```

When I run the tests from within Xcode (currently using the 14.3 beta), the tests trap on jemalloc - `je_free_default` in the stack trace.
<img width="1138" alt="Screenshot 2023-02-18 at 11 35 22 AM" src="https://user-images.githubusercontent.com/43388/219884803-e26c2c0e-f08a-469d-a427-fdcf479f6942.png">

Is there something additional I should be doing re: jemalloc?

I'm not familiar with using custom allocators and what the requirements are around that, so I suspect I'm missing something in my setup to support running `swift test` without issue.

**Comment by hassila** [comment]
Yeah… unfortunately this seems to be a problem with the macOS proprietary version of xctest - I’ve reported it to Apple with a feedback which was subsequently closed as they thought it was a problem with jemalloc. I’ve the had help [investigating this with the jemalloc engineers](https://github.com/jemalloc/jemalloc/issues/2362) which seems to point out xctest as passing a pointer to free that was not originally allocated by jemalloc… I’ve commented on the original Apple feedback but got no reply after that. 

The open source xctest version works fine on Linux though (so we currently live on the CI Ubuntu runner or local multipass/Ubuntu testing at the moment) and that would be the current recommended way to run the test suite (still hoping to get someone at Apple to take a second look at it, as it’d be much better to be able to run it on macOS too…).

**Comment by hassila** [comment]
If anyone files a feedback on this, please reference FB12061292.

**Comment by hassila** [comment]
Fixing this in #127 - to run test suite on macOS:

`BENCHMARK_DISABLE_JEMALLOC=1 swift test`

I haven't found a way to pick up environment variables properly in Xcode (hints appreciated) so it works, but if running the benchmark package in Xcode and simply setting the variable properly in Package.swift, the test suite can be run within Xcode too.

**Comment by heckj** [comment]
Thanks @hassila
