### ISSUE TITLE
CLI exploration of the `swift package benchmark` command doesn't exist

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#61]
I found the commands to invoke benchmarks in the online docs, but I was hoping to be able to invoke something like: `swift package benchmark --help` to get a list of the commands and how to use them, or perhaps `swift package plugin benchmark -help`. 

Getting to CLI arguments exposed is what I was after - the DocC compiler plugin exposes some of its help in this fashion. Is that something possible here?

**Comment by hassila** [comment]
Yes, it's definitely on my to-do. Basically, the plugin can't use Swift Argument Parser with the nice auto-generation of help, so I'll need to write up a page manually - looking at some minor usability improvements first but will be there soon, thanks for the ping!
