### ISSUE TITLE
no benchmark output from `swift package benchmark`

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#62]
I'm sorry to be popping open a bunch of issues here - if there's a better place to ask for guidance, I'm totally game.

I tried adding a simple benchmark setup to a library I'm working on, and adding it as an external package that imports mine with a local reference. That all appears to work correctly, `swift package resolve` is happy, `swift build` works, and `swift package benchmark` appears to work as well - except that there's no benchmark data visible.

The output I get from the command is:
```bash
Building for debugging...
Build complete! (0.35s)
Building targets in release mode for benchmark run...
Build complete! Running benchmarks...

```

If I run `swift package benchmark list`, it's the exact same output.

(this is with package-benchmark 0.8.0, and swift 5.8 (installed from Xcode 14.3 beta) on macOS with an M1 processor)
swift -version:
```
swift-driver version: 1.75.1 Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)
Target: arm64-apple-macosx13.0
```

The source of what I've done is public if you're willing to take a look, or I'd be happy to have any guidance on how to debug what's happening. I suspect I may be using the plugin in a manner that was slightly unexpected.

The work in progress can be seen for a quick view of how I added things at https://github.com/heckj/CRDT/pull/34/files, and it should be very easy to reproduce with these steps:
```
git clone https://github.com/heckj/CRDT -b benchmark2
cd CRDT/ExternalBenchmarks
swift package resolve
swift package benchmark
```

**Comment by heckj** [comment]
Oh - I should mention: When I run the executable directly, it does provide some output. `.build/release/ExternalBenchmark` reports:

(line breaks manually inserted - otherwise this was insane to view on Github)
```
Debug result: [
Benchmark.BenchmarkResult(metric: Time (wall clock), timeUnits: ms, measurements: 1, warmupIterations: 3, thresholds: nil, percentiles: [
Benchmark.BenchmarkResult.Percentile.p99: 1230, Benchmark.BenchmarkResult.Percentile.p0: 1230, 
Benchmark.BenchmarkResult.Percentile.p100: 1230, Benchmark.BenchmarkResult.Percentile.p90: 1230, 
Benchmark.BenchmarkResult.Percentile.p75: 1230, Benchmark.BenchmarkResult.Percentile.p25: 1230, 
Benchmark.BenchmarkResult.Percentile.p50: 1230]),
 Benchmark.BenchmarkResult(metric: Time (user CPU), timeUnits: ms, measurements: 1, warmupIterations: 3, thresholds: nil, percentiles: [
Benchmark.BenchmarkResult.Percentile.p99: 1228, Benchmark.BenchmarkResult.Percentile.p25: 1228, 
Benchmark.BenchmarkResult.Percentile.p75: 1228, Benchmark.BenchmarkResult.Percentile.p100: 1228, 
Benchmark.BenchmarkResult.Percentile.p0: 1228, Benchmark.BenchmarkResult.Percentile.p90: 1228, 
Benchmark.BenchmarkResult.Percentile.p50: 1228]), 
Benchmark.BenchmarkResult(metric: Time (total CPU), timeUnits: ms, measurements: 1, warmupIterations: 3, thresholds: nil, percentiles: [
Benchmark.BenchmarkResult.Percentile.p99: 1231, Benchmark.BenchmarkResult.Percentile.p50: 1231, 
Benchmark.BenchmarkResult.Percentile.p75: 1231, Benchmark.BenchmarkResult.Percentile.p90: 1231, 
Benchmark.BenchmarkResult.Percentile.p100: 1231, Benchmark.BenchmarkResult.Percentile.p0: 1231, 
Benchmark.BenchmarkResult.Percentile.p25: 1231]), 
Benchmark.BenchmarkResult(metric: Time (system CPU), timeUnits: μs, measurements: 1, warmupIterations: 3, thresholds: nil, percentiles: [Benchmark.BenchmarkResult.Percentile.p50: 2376, ...])]
```

**Comment by hassila** [comment]
https://github.com/heckj/CRDT/pull/35

**Comment by heckj** [comment]
Thank you - 

The PR (in case anyone else stumbles into the same poor assumption I made) changes the location of the benchmark sources to be stored within a directory named `Benchmarks`, and then references them with `path:` in the Package.swift so that the compiler can find this specific location. The `swift package benchmark` plugin uses the specific location of `Benchmarks` to find and run any existing benchmarks.
