### ISSUE TITLE
naming for iterations and/or duration

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#65]
Working through writing a few sample benchmarks, I was exploring `Benchmark.defaultConfiguration.desiredIterations`, `Benchmark.defaultConfiguration.desiredDuration`, and how they relate to each other.

I do think the names could be improved by renaming them to `maxIterations` and `maxDuration`, respectively. I'm also thinking that as we cobble the documentation, expanding on `Benchmark.Configuration` (and maybe the article `WritingBenchmarks.md`), it would be worth calling out specifically that the running will go until the first of these two are hit.

And just to double check - if you specify warmupIterations on the configuration, does that take place before either the iterations vs. duration markers are measured?

**Comment by hassila** [comment]
Agree it would be a nice improvement!

> And just to double check - if you specify warmupIterations on the configuration, does that take place before either the iterations vs. duration markers are measured?

Yes it does, it's completely outside the measurement.
