### ISSUE TITLE
feature request: text-based output without all the pretty around it

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#90]
I was applying package-benchmark to a comparison effort between a number of different existing libraries and external packages, so compare speeds of how they did their work. When I was dumping the output, I found that I wanted to sort and view the results as an ordered list, and then wanted to go grab and knock together some simple graphs for the comparison between the different libraries. The TextTable output, which looks so great, was completely in the way, and I ended up having to do quite a lot of text editing to grab the data out into a spreadsheet, which I then used to re-order things, make charts, etc.

(I also found that TextTable was clipping some names, as I was getting pretty descriptive there)

The request is for a text based output that applies a bit more directly in this direction, or even a plain `.csv` output - something that can be easily copy & pasted, or a .csv output that you could open with spreadsheet-of-your-choice kind of setup.

I did look at the `tsv` format output, but didn't quite know what it was an how to interpret it - and it wasn't in any sort of obvious columnar form - so I don't think that applies.

**Comment by hassila** [comment]
I think we should add a .csv format usable for direct import to spreadsheets - are you thinking percentiles or raw data?

**Comment by hassila** [comment]
But to compare speeds I'd suggest also trying .jmh and the online analyzer (or histogram,percentiles and loading multiple files to that analyzer)

**Comment by heckj** [comment]
In my case, I was after the percentiles (and associated raw numbers at those percentiles) - the equivalent bits that get presented after a run, just easier to resort and use as sourcing for making quick comparison charts. I haven't used the online analyzer, but I'll give that a go!

**Comment by heckj** [comment]
Wow - that JMH comparison setup is _really_ nice, and very quickly provided some of the detail I was after! We should absolutely reference that in the documentation, with a link to that online view (assuming that's not in the end abusive of someone's service)!

**Comment by hassila** [comment]
There should be a link to it in main already (and on the landing page) :-) ! But I'll add one more - agree, it isn't bad at all.

**Comment by hassila** [comment]
Adding percentiles 0-100 output as an alternative in https://github.com/ordo-one/package-benchmark/pull/102 - it worked more-or-less when pasted into a spreadsheet too - although numbers had some issues with decimal points, but may be Swedish locale - will try a bit more.

**Comment by heckj** [comment]
Ooh - nice, I'll pull that branch down and try it out with some of my local bits. I've got a handy testbed set where I'm comparing the speeds of various implementations of pseudo-random number generators, which was the inciting use case for the request.

**Comment by hassila** [comment]
Cool, would be great with some additional testing. Perhaps you could go for https://github.com/ordo-one/package-benchmark/pull/103 branch - it should be the latest and greatest right now really. :-)

**Comment by hassila** [comment]
Maybe should just skip the 99.999(99) percentile in output and keep it simpler. Then import to numbers would be a breeze. WDYT?

**Comment by heckj** [comment]
using `--format histogramSamples`, which looks to be the replacement for `--format tsv`, is still just a single line of values, and kind of oddly with the filename extension of `.raw.tsv` - no header, so it's hard to know what the values are unless you're _really_ familiar with the benchmarks that were written.

The `--format histogramPercentiles` was definitely easier to parse - and had headers. The extra 9's didn't do anything for me, but in this mode I'm not as interested in the long-tail latencies - so for my purposes, I'd be totally fine to see it.

The extension pattern on the `histogramSamples` is a little different yet - listing the metric in the name now as a sort of extension, and then on into detail (example: `.throughput.histogram.percentiles.tsv`). I think `percentiles` in the chain is redundant, as it's well labeled in the tab-sep-values.

Oh - and thank you for fixing the `--grouping metric` headers!

**Comment by hassila** [comment]
Thanks for trying it out!

histogramSamples is just all the raw histogram samples scaled to the time/SI unit in use (really for external processing using eg. Youplot or spreadsheet, but maybe a header with unit information would be good.)

For the 0-100 percentiles - I'll add support for putting the multiple baselines (if provided) into the same output, will think a bit perhaps should tweak how output is generated based on grouping.

**Comment by hassila** [comment]
> The extension pattern on the histogramSamples is a little different yet - listing the metric in the name now as a sort of extension, and then on into detail (example: .throughput.histogram.percentiles.tsv). I think percentiles in the chain is redundant, as it's well labeled in the tab-sep-values.

This was to separate 'samples' from 'percentiles' as both are .tsv formats - I've added a header and fixed the scaling of the sample data now so it should be more understandable. I also killed off the extra .999:s
