### ISSUE TITLE
bug: fatal error while running default compare

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#91]
Working on the `main` branch (commit: 7d6f5f926367ebde06dc33a7561c3874d5424a8f), and running through the documentation and trying out the various examples to double-check them, I found that a default baseline compare was failing:

reproduction:
```bash
swift package --allow-writing-to-package-directory benchmark baseline update
swift package benchmark baseline compare
```

Output of failure:
```bash
Building for debugging...
Build complete! (0.21s)
Building benchmark targets in release mode for benchmark run...
Building HistogramBenchmark
Building BenchmarkDateTime
Building Basic
Build complete!
Swift/RangeReplaceableCollection.swift:870: Fatal error: Can't remove last element from an empty collection
error: plugin process ended by an uncaught signal: 5 <command: /usr/bin/sandbox-exec -p '(version 1)
(deny default)
(import "system.sb")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath "/private/tmp")
    (subpath "/private/var/folders/8t/k6nw7pyx2qq77g8qq_g429080000gn/T")
)
(deny file-write*
    (subpath "/Users/heckj/src/package-benchmark")
)
(allow file-write*
    (subpath "/Users/heckj/src/package-benchmark/.build/plugins/Benchmark-Plugin/outputs")
    (subpath "/Users/heckj/src/package-benchmark/.build/plugins/Benchmark-Plugin/cache")
)
' /Users/heckj/src/package-benchmark/.build/plugins/Benchmark-Plugin/cache/Benchmark_Plugin>, <output:
'Building benchmark targets in release mode for benchmark run...
Building HistogramBenchmark
Building BenchmarkDateTime
Building Basic
Build complete!
Swift/RangeReplaceableCollection.swift:870: Fatal error: Can'\''t remove last element from an empty collection
'>
```

Workaround: if you name the baseline, there's no issue - so running `swift package benchmark baseline compare default` works.

**Comment by hassila** [comment]
Yes sorry about that - I'm in the middle reworking some of the baseline stuff (specifically splitting compare and threshold checks to two different commands) and one realization was that I think we shouldn't have a default baseline but only work with names ones for clarity and consistency. There's a separate PR up right now that has some minor issues remaining on the branch names polish-text-output or similar- will merge it early next week). 

Thanks for reporting this!
