### ISSUE TITLE
bug: tab separated values output may be broken

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-benchmark#92]
On the `main` branch, I ran through the various formats and exported them to verify all the formats worked as expected. The `tsv` case looks like it might well be "broken", although I don't have historical data to compare easily.

When I looked through the files written, there was only ever a single value in a long series down the list. For example, the exported file `default.HistogramBenchmark.Mean.Syscalls_(total).tsv` (attached for convenience) looks almost meaningless in it's output with the variety of numbers, and flipping through the metrics makes me suspect it's iterating incorrectly.

If you flip through the various "Mean Syscalls" files in the attached zip, it looks like they build on each other - which doesn't seem correct.

[Mean.Syscalls.zip](https://github.com/ordo-one/package-benchmark/files/10946870/Mean.Syscalls.zip)

**Comment by hassila** [comment]
Yeah, tsv needs some TLC (also to support multiple baselines for comparisons), thanks for the report.

**Comment by hassila** [comment]
You are absolutely correct, fixing this in https://github.com/ordo-one/package-benchmark/pull/99
